[ui]
tree_folder = /home/cruxible/Desktop
last_file = /home/cruxible/cyon/pyra_lib/gtk_lib/pyra_notes.py

[highlight_group_1]
keywords = print for while if elif else with finally
color = #ffb000

[highlight_group_2]
keywords = def class return import from
color = #5fd7ff

[highlight_group_3]
keywords = try except self
color = #8fd3ff

[highlight_group_4]
keywords = True False None
color = #ff4444

[highlight_special]
color_lime = #c8ff00
color_coral = #ff9966
color_comment = #6a5acd
color_dot_left = #ffffff
color_dot_right = #ffb000

[highlight_group_5]
keywords = display position margin padding border color background width height font font-family font-size font-weight
color = #ff88ff

