[session]
notes_dir=/home/cruxible/cyon
open_files=/home/cruxible/cyon/src/cyon_notes.c;
active_tab=0

[editor]
font_size=23
tree_hidden=false
tree_pane_position=278
window_width=492
window_height=633

[tts]
piper_path=/home/cruxible/pyra_env/bin/piper
model_dir=/home/cruxible/cyon/piper_models
voice_joe_model=en_US-joe-medium.onnx
voice_lessac_model=en_US-lessac-medium.onnx
voice=joe

[highlight_group_1]
keywords=for while if elif else with break continue pass yield raise assert printf g_print snprintf system echo exit return
color=#ffb000

[highlight_group_2]
keywords=def class import from as lambda global nonlocal del
color=#5fd7ff

[highlight_group_3]
keywords=try except finally self super
color=#8fd3ff

[highlight_group_4]
keywords=True False None NotImplemented Ellipsis sizeof NULL nullptr true false
color=#ff4444

[highlight_group_5]
keywords=display position margin padding border background width height font font-family font-size font-weight align justify flex grid overflow transition transform opacity cursor
color=#ff88ff

[highlight_group_6]
keywords=len range open map filter list dict set tuple int float str bool type isinstance enumerate zip sorted reversed sum min max abs round hasattr getattr setattr callable
color=#00ffaa

[highlight_group_13]
keywords=gboolean gint gchar GtkWidget GtkWindow GtkBox GtkButton GtkLabel
color=#8fd3ff

[highlight_group_14]
keywords=expanduser join append extend insert pop update get items keys values function source export alias unset
color=#5fd7ff

[highlight_group_7]
keywords=and or not in is
color=#ffd700

[highlight_group_8]
keywords=os sys subprocess pathlib read write mkdir remove rename chmod chown stat glob shutil copy move cd ls cat grep sed awk find ps kill sudo apt git
color=#00eaff

[highlight_group_9]
keywords=eval exec compile __import__ malloc free calloc realloc goto
color=#ff5555

[highlight_group_10]
keywords=breakpoint help dir vars globals locals __name__ __file__ __doc__ __all__ __init__ __main__
color=#c792ea

[highlight_group_11]
keywords=void static const char unsigned signed long short struct union enum typedef extern inline auto register volatile restrict
color=#8fd3ff

[highlight_group_12]
keywords=include define ifdef ifndef endif pragma undef
color=#ffb347

[highlight_special]
color_lime=#c8ff00
color_coral=#ff9966
color_comment=#6a5acd
color_dot_left=#ffffff
color_dot_right=#ffb000
color_steel=#8fd3ff
